### ISSUE TITLE
Deprecation gulp-foreach

### ISSUE THREAD

**Issue by sketchthat** [timhuff/gulp-task#1]
`gulp-foreach` is deprecated.

When installing `gulp-task` the following npm warnings appear.

```
npm WARN deprecated gulp-foreach@0.1.0: Either use gulp-tap or gulp-flatmap, depending on your needs
npm WARN deprecated gulp-util@2.2.20: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
```

**Comment by timhuff** [comment]
Hi @sketchthat - this library isn't really maintained anymore. I wrote it years ago and have since moved on to webpack. However, I realize that there are legacy apps out there that might depend on it. If you put in a PR to update this, I'll merge it. Unfortunately, I don't have time at the moment to do so myself.

**Comment by sketchthat** [comment]
I'll close this, I was using the wrong version of gulp which caused the issue. My mistake.
